# Generated by Django 4.0.3 on 2022-03-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('IN PROGRESS', 'In progress'), ('FIXED', 'fixed'), ('COMPLETED', 'completed')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
    ]
