# Generated by Django 4.0.3 on 2022-03-13 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='progrss_id',
            new_name='progress_id',
        ),
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
    ]
