# Generated by Django 4.0.3 on 2022-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_progrss_id_progress_progress_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='points',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
