# Generated by Django 4.0.3 on 2022-03-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_progress_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.ForeignKey(choices=[('PENDING', 'pending'), ('IN PROGRESS', 'In progress'), ('FIXED', 'fixed'), ('COMPLETED', 'completed')], null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
    ]
