# Generated by Django 4.0.3 on 2022-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_progress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('IN PROGRESS', 'In progress'), ('FIXED', 'fixed'), ('COMPLETED', 'completed')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
    ]
