# Generated by Django 4.0.3 on 2022-07-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_task_status_alter_progress_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocker_answer',
            old_name='query',
            new_name='blocker',
        ),
    ]
