# Generated by Django 4.0.3 on 2022-07-03 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_query_blocker_answer_blocker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
